### ISSUE TITLE
RFC: Type reflection support? Perhaps like typeof operator?

### ISSUE THREAD

**Issue by creatorrr** [mint-lang/mint#104]
Hey guys!

Not sure if something similar is already planned but it would be useful to have basic type reflection support in `mint`. As far as I understand, this is only possible using inlined javascript at the moment. Not sure how this would be done but happy to brainstorm and work on a PR if there's interest.

Example use cases:

 - Adding a function that can generate say a `protobuf` interface from a mint `record` specification.
 - Polymorphic functions on complex types?

This could be achieved at both the language level and the runtime level. Thoughts on which is better?
Possible syntax:

```
record Score {
  value: Number
  updatedAt: Time
}

record CalvinballScore {
  calvin: Score,
  hobbes: Score
}

fun genProtoBuf(rec : Record) : ProtoBufInterface {
  /* somehow convert record spec */
}
```

**Comment by gdotdesign** [comment]
This is a very difficult subject. 

Currently types are only used for type checking and because of that they are only available at compile time, so the types are not real in the sense that they don't have a definition. 

Let's take the the `SearchParams` type as an example. A `SerachParams` can only be created with this function here: https://github.com/mint-lang/mint-core/blob/master/source/SearchParams.mint#L4 (using inlined JavaScript) and there is no definition of a `SearchParams` type.

Any function that has an argument for `SearchParams` will only compare the name and nothing else. It is safe as long as it's not messed with inline JS.

So that's some background on how types work, now let's see the two use cases which you mentioned:
*  I'm not very versed of the `protobuf` implementation or usage but I assume it's similar on how JSON decoding / encoding works. Mint has support for auto encoding and decoding of JavaScript objects (`Object` type) for simple data structures (meaning records, literals, arrays and hashes) https://github.com/mint-lang/mint/blob/master/src/utils/decoder.cr#L60. This `Object` type can be used to generate / parse a JSON string by using the `JSON` JavaScript object). I guess there is a JavaScript library for `protobful` that can use this `Object`.

What could be exposed somehow is this auto generation feature.

* > Polymorphic functions on complex types?
  
  Function overloading is theoretically is possible in a way that doesn't require runtime checking which I think worth a look.

**Comment by creatorrr** [comment]
Gotcha @gdotdesign . In that case, some other possibilities for the protobuf (Google's typed rpc protocol) use case:
 - generate stubs separately by getting type data from mint parse tree. This is probably simplest but doesn't allow runtime changes
 - (wild idea) perhaps by adding simple macros support to the language?
 - an approach like you mentioned above

@gdotdesign Pros / cons / thoughts?

**Comment by gdotdesign** [comment]
I'm closing this issue for now, there won't be any type reflection support for the foreseeable future.
