### ISSUE TITLE
Feature Request: Recursion for local functions

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint#179]
A function defined in the `where` block cannot call itself. Compiler properly detects the situation but errors with:
 > Recursion is not supported at this time by the language.

It's a common pattern to call a helper function that receives more arguments than a module function. I think we should have it. What are the obstacles?

**Comment by gdotdesign** [comment]
There is no obstacle here, since normal function recursion is solved by using it's static type definition, we can do the same thing here, just need to code it.

If anyone wants to give this a go before I can get to it, here are some pointers:
- here (https://github.com/mint-lang/mint/blob/master/src/type_checker.cr#L223) is where the type-checker does the check for recursion, we need to check for `WhereStatement`
- here (https://github.com/mint-lang/mint/blob/master/src/type_checkers/function.cr#L6) is the `static_type_signature` of a function, we need to do the same for `WhereStatement`

**Comment by Namek** [comment]
Can I request a release with this? Thanks.

**Comment by gdotdesign** [comment]
Sure, I'll try to do a release in a few days.
