### ISSUE TITLE
Request: Auto-format sooner (before type-check)

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint#211]
It seems that built-in formatter does it's job only when program is properly compiled. I tend to abuse this functionality and it fails on me really hard when I implement something more complicated. For example, when a function returns should return a record, I have to instantiate the record somewhere to return it properly. However, I tend to design steps of algorithm first, and only later fill data holes and so on.

See another example:
```
fun recursivelyGenerateMyThing(pos : Position, stepsLeft : Number, thing : ComplicatedThing) : ComplicatedThing {
  if (stepsLeft == 0) {
    thing
  } else {
    /* TODO complicated algorithm with multiple nested ifs */
    try {
      0
    }
  }
}
```

Above, although `0` (zero) does not match the `ComplicatedThing` record it's already **syntax-valid**. It's just not type-valid.

So I would expect auto-formatter to work sooner, at least when syntax seems OK to the compiler. It would be even better if I had not to put `0` but that would be another potential step.

**Comment by gdotdesign** [comment]
This is the way the development server should work right now:
- in the reactor we pass the formatter proc to the `Ast::Watcher` :arrow_right: https://github.com/mint-lang/mint/blob/master/src/reactor.cr#L34
- the watcher runs the proc when a parsing is successful :arrow_right: https://github.com/mint-lang/mint/blob/master/src/utils/ast_watcher.cr#L64

However since Mint does not have a tokenizer (where most other languages do) it is actually a syntax error not having an expression in a `try`. 

I'm not sure what can be improved at this point.

**Comment by Namek** [comment]
Actually, this currently seem to work quite well. I'll be closing this for now. Thanks.
