### ISSUE TITLE
Instalation on MacOS stuck on "make" command

### ISSUE THREAD

**Issue by pawel-miczka** [mint-lang/mint#218]
Hi,

Today I wanted to install mint-lang on MacOS but installation stuck on **make** command. Here is screenshot from my terminal. I tried to install it from homebrew-community/alpha and it also sticks on **make** command

![image](https://user-images.githubusercontent.com/5631954/76693270-8efd1400-6662-11ea-938d-9428cbf70daa.png)

**Comment by emeraldsanto** [comment]
I've been trying to install on macOS for a few hours now and I've also come across this problem.

**Comment by s0kil** [comment]
A temporary work around is to use a built binary https://github.com/mint-lang/mint/releases/tag/0.8.0

**Comment by gdotdesign** [comment]
The Homebrew package is maintained in https://github.com/homebrew-community/homebrew-alpha maybe we should create an issue there?

**Comment by gdotdesign** [comment]
@Acciaiodigitale

**Comment by Acciaiodigitale** [comment]
Hi @pawel-miczka you are using the old repository.

Try with:

```
brew tap homebrew-community/alpha
brew install mint-lang
```

**Comment by Acciaiodigitale** [comment]
...but make of llvm can take a looong time....

**Comment by pawel-miczka** [comment]
Ok I'll try but I mentioned in post that I tried install it via homebrew-community/alpha and it also stuck. Maybe somehow it will work now 🤣 - I will send you some report

**Comment by Acciaiodigitale** [comment]
Sorry @pawel-miczka, I only see the screeshot.....

I personally don't have a Mac now and I tested only on Linux. 
I don't have problem there.
Open an issue on homebrew-community please.

**Comment by pawel-miczka** [comment]
Ok, no problem, thanks :)

**Comment by Sija** [comment]
@pawel-miczka Works for me, you might have some problems with your setup.

I see two fishy things:
- `==> Installing mint-lang from acciaiodigitale/alpha` - should be `==> Installing mint-lang from homebrew-community/alpha`
- `Warning: Building llvm from source` - you should have llvm poured from bottle, otherwise you're in for some serious time warp...

I'd suggest doing `brew rm mint-lang` and trying again - this time making sure everything is as it should be.

**Comment by pawel-miczka** [comment]
First I tried to install it via homebrew-community/alpha and it stuck on make command. Then I found acciaiodigitale repo and tried with it - nope, it still stuck. Now I came back to homebrew-community/alpha and tried it install again but still - no success. 

Now I typed ```brew rm mint-lang``` and get
```
Error: No such keg: /usr/local/Cellar/mint-lang
```
so I think its not installed still.
I don't know - maybe I will try later 😄

**Comment by s0kil** [comment]
@pawel-miczka Did you resolve this issue?

**Comment by pawel-miczka** [comment]
Nope. I didn't tried to reinstall it again.

**Comment by gdotdesign** [comment]
@pawel-miczka pinging, so we can close the issue  :slightly_smiling_face:

**Comment by gdotdesign** [comment]
Closing since there is a new release since the issue was reported, and also did not get an answer.

**Comment by zephraph** [comment]
FWIW I'm seeing this today. 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3087225/80246755-f2ec0280-863a-11ea-9439-9944b1d85f3f.png">

I let the make command spin for about an hour before killing it and retrying. It's been about 45 minutes now. It does look like building llvm from source is the core issue here though.

**Comment by zephraph** [comment]
Okay, I figured this out. I'll PR some doc updates because this was an _incredibly_ frustrating experience which is no fault of mint-lang and I'd hate for people not to try it out due to this. 

@pawel-miczka as @Sija said, the installing from source part should (and can) be avoided. It takes _hours_ to install llvm from source. 

There is a hint in the output though:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3087225/80253488-5d0aa480-8647-11ea-9763-2a2f8ed464e6.png">

Some googling lead me to [this issue](https://github.com/Homebrew/homebrew-core/issues/2502). CLT is Apple's command line toolkit for XCode. You can see if you have it installed already by running `brew config`. There will be a `CLT` field that will likely say `N/A` if you're having this long install time. 

So first, we want to get CLT. I downloaded that from [apple](https://developer.apple.com/download/more/). You've got to sign in with an apple id, but I don't think you have to have an active developer account (I don't). I just downloaded the latest CLT which is 11.4.1 (shown below)

<img width="738" alt="image" src="https://user-images.githubusercontent.com/3087225/80253713-c2f72c00-8647-11ea-86bd-c48bad31217b.png">

After that installs, just do `brew install mint-lang` again like normal and it'll finish in around 6 minutes or so.
