### ISSUE TITLE
Required property does not generate a type checker error

### ISSUE THREAD

**Issue by mszmurlo** [mint-lang/mint#242]
Hi,

I understand from the documentation: _A property can be required by leaving out the default value: This means when using this component this property must be set, if it's not then the type checker will show you an error._ that the block below should make the type checker scream:

```
component Main {

  property color  : String
  
  fun render : Html {
  
      <button onClick={(event : Html.Event) : String {Debug.log("#{color}")}}>
        "Click ME!"
      </button>
    
  }
}
```
Yet, I get a `null` in the console. I started to play with Mint about 2 weeks ago so it's very possible that  my understanding is wrong, or there is a bug.

**Comment by gdotdesign** [comment]
This is something I did not foresee :joy: 

So you can leave the default value of a property out, but for the `Main` component it does not make sense, since it doesn't take any properties because it's rendered directly.

In the next version properties on `Main` will be not allowed (and show an error) for this reason.

Let me know if it makes sense :slightly_smiling_face:

**Comment by mszmurlo** [comment]
It certainly does!

**Comment by gdotdesign** [comment]
I'll just keep this open for the reminder to implement the error.
