### ISSUE TITLE
Calling a component with case insensitive shows a blank page

### ISSUE THREAD

**Issue by G4BB3R** [mint-lang/mint#29]
Step 1: Enter in the link https://www.mint-lang.com/try (I use google chrome)
Step 2: Change `<Counter disabled={false}/>` to `<counter disabled={false}/>`
Step 3: Compile and the resulting page is blank.

Off Topic Bonus: type errors are inverted! 
```
I was expecting:
Htmlxd
Instead it is:
Html
```

**Comment by gdotdesign** [comment]
This is the correct behavior.

`<counter disabled={false}/>` is an HTML tag, it's resulting in a blank page, because it does not have any content.

The rule is that components are starting with an uppercase letter, HTML tags start with a lowercase letter.

> Off Topic Bonus: type errors are inverted!

Can you show me of what code did result in this error?

**Comment by G4BB3R** [comment]
Just change  `fun render : Html {` to  `fun render : Htmlxd {`

**Comment by gdotdesign** [comment]
Then the error is correct :)

The compiler was expecting `Htmlxd` which is a valid type (types are only needed for type checking and are not needed to be explicitly declared) but the render function returns `Html` hence the error.
