### ISSUE TITLE
[RFC] Make the receiver of the piped calls (|>) always the first argument

### ISSUE THREAD

**Issue by Sija** [mint-lang/mint#314]
At the moment it's being passed as the last one.

Passing it as the first argument would IMO give the following benefits:
- Predictable calling convention - _first_ argument position is constant, in contrary to the _last_ - which requires knowing all the others
- Conformity with other languages using pipe operator - see Elixir
- More natural looking calls - `Array.any([1, 2, 3], (number : Number) : Bool { number % 2 == 0 })`

**Comment by gdotdesign** [comment]
I don't know which is better, I'll do some reasea

**Comment by gdotdesign** [comment]
In Mint it's the last mostly because of partial application:

```
module A {
  fun (a : String, b : Number, String) {
    a + Number.toString(b)
  }
}

A.a            /* Function(String, Number, String) */
A.a("Hello")   /* Function(Number, String) */

0 |> 
A.a("Hello")  /* "Hello0" */
```

So basically the pipe is: `x |> f <=> f(x)` meaning its a syntax sugar for method calls (https://github.com/mint-lang/mint/blob/master/src/ast/pipe.cr#L13)

----------------------

Did a little research what other languages do:

**ReasonML**:

They have two operators `->` for first `|>` for last.

```
x -> f(y, z) <=> f(x, y, z)
x |> f(y, z) <=> f(y, z, x)
```

**Elm**:

It's the last and they have two `|>` and `<|`.
```
x |> f <=> f x
f <| x <=> f x
```

**PureScript**

It's the last.
```
x # f <==> f x
```

**F#**:

It's the last.
```
x |> f = f x
```

**Elixir**:

It's the first.

```
x |> f = f x
```

**Haskell**:

It's the last.

```
x . f = f x
```

----------------------

So this is basically function composition https://en.wikipedia.org/wiki/Function_composition_(computer_science)

What I was thinking on making it easier to use is:

- keep it as putting it in the last argument
- have a placeholder element `_` for where the argument would go, basically you could specify it's location:

```
"left side argument" 
|> A.a("first argument", _, "last argument")
``` 

----------------------

I'm probably somewhat biased because I only used Elm before and there it's the last.

Let me know (anyone) your ideas and preference :)

**Comment by hazon** [comment]
I guess a better approach would be to introduce a second operator `<|` like Elm does.
Using the placeholder, as you suggests, could also be a viable option, however it would be confusing if you wanted to use partial application of a function... where you might have multiple `_` params that you wanted to inject later on.
