### ISSUE TITLE
Map gets serialized in JSON as array instead of object.

### ISSUE THREAD

**Issue by hazon** [mint-lang/mint#326]
In mint 0.10.0 Map implementation is based on arrays (see "Map is now using arrays for the implementation" #268).
JSON serialization (e.g. when calling a REST API) used to serialize Map as Object.
Now an array is returned (in case of an empty map) and this breaks server-side JSON deserialization.
Is there a way to force a map to serialize as an object?

Thanks in advance and great work! I love Mint.

**Comment by gdotdesign** [comment]
> JSON serialization (e.g. when calling a REST API) used to serialize Map as Object.

This is a regression for sure, sorry about that, I'll try to reproduce the original behaviour in the next release (and keeping the implementation as Arrays). 

Since maps are represented as an array of two dimensional arrays (`[["key", "value"], ["key2", "value2"]]`) you can convert them to a JavaScript `Map` before serialization: `new Map(#{yourMap})`.

Here is an example in the sandbox: https://sandbox.mint-lang.com/sandboxes/RNZhRb8Z1crunQ

------------------------------------------------


> Thanks in advance and great work! I love Mint.

Thanks :wink:
