### ISSUE TITLE
Confusing error when trying to add styles to custom components

### ISSUE THREAD

**Issue by matthewmcgarvey** [mint-lang/mint#327]
I've been trying out mint and have enjoyed it so far!

I tried adding a style to a component in my project and got back this error when I would have expected a more explicit error that states that styles cannot be applied to custom components.
<img width="1117" alt="CleanShot 2020-10-03 at 16 01 18@2x" src="https://user-images.githubusercontent.com/17329408/95001719-5e46e280-0592-11eb-8c84-d6d66f6aee4a.png">

**Comment by gdotdesign** [comment]
> I've been trying out mint and have enjoyed it so far!

That's great to hear!

> I tried adding a style to a component in my project and got back this error when I would have expected a more explicit error that states that styles cannot be applied to custom components.

This is a syntax error. The parser doesn't parse `::base` (since components can't have styles, like elements can) it just parses until `<Components.Content` and expects something else, this makes it fast and it can return early with an error.

The error in this case is indeed misleading and should be changed to something like this:
```
I could not parse further, I've was looking for one of the following:

- an attribute for the component
- a reference to the component "as component"
- "/>" for self closing components
- ">" for none self closing component

You can read more about components here: https://www.mint-lang.com/guide/reference/components
```

**Comment by matthewmcgarvey** [comment]
I guess I forgot to link the PR, but this was completed by https://github.com/mint-lang/mint/pull/329
