### ISSUE TITLE
Time JSON serialization changed

### ISSUE THREAD

**Issue by hazon** [mint-lang/mint#357]
Apparently JSON serialization of Time has changed between 0.9.0 and 0.11.0.
I found it the hard way... my back-end could no longer JSON-decode objects.

version 0.9.0:
... "createdAt":"2021-01-15T08:46:41.755Z" ...

version 0.11.0:
... "createdAt":1610700247350 ...

Is there a way to cause Mint 0.11.0 to serialize Time as ISO string instead of number?

**Comment by gdotdesign** [comment]
Hi, yes this changed in 0.10.0 or more specifically `Time` is now explicitly serialized (encoded) instead of just using the JavaScript `Date` object. This is the commit that changed this: https://github.com/mint-lang/mint/commit/0a85fa522dc9d9ea2300d2c60231517c4ad8c0ec

There is no global way of changing this behaviour of the automatic encoding (only by modifying the runtime), so the only other option is to write encoders by hand if you want to keep the same interface.

The encoded value is the milliseconds since epoch: _00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970_ which is what you get when converting a JavaScript `Date` to number `+new Date()`. 

We can change this in a future release if it makes more sense to use an ISO format (by popular vote).

**Comment by hazon** [comment]
Thanks for the answer, I'll see what I can do.
If there's a chance to vote, I'll surely vote for ISO 8601. :-)

However now there's a mismatch between the behavior of "encode" as opposed to Object.Encode.time(), isn't there?

**Comment by gdotdesign** [comment]
> However now there's a mismatch between the behavior of "encode" as opposed to Object.Encode.time(), isn't there?

Yes :) I think I forgot to change that.

**Comment by Sija** [comment]
I'd vote for an ISO string too :)
