### ISSUE TITLE
Incorrect fetching from service-worker

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint#370]
When the service-worker doesn't find a cache for a file, it responds with the file `index.html`.

The problem is that **it doesn't check if the requested file is one of the cacheable files**.

If not, it should fetch the request instead of serving from the cache.

**Comment by gdotdesign** [comment]
This is intentional.

In order for the routes to work we need to serve `index.html` for everything that is not cached (not a static file): https://github.com/mint-lang/mint/blob/master/src/utils/service_worker.cr#L37 this only works on **same origin requests**.

We can make this a bit smarter and only return the `index.html` which matches one of the routes.

-----

I'm curious what issue is this causing you?

**Comment by Eternahl** [comment]
> I'm curious what issue is this causing you?

On my backend ( static server ), i have a _PHP_ script file, along with the content of "_dist_" 
The script isn't executed when the service-worker take the control

> We can make this a bit smarter and only return the index.html which matches one of the routes.

This should probably solve the problem

**Comment by gdotdesign** [comment]
One thing you can do now is to disable the service worker with the `--skip-service-worker` flag, but if you do then you need to configure your server to return the `index.html` for the routes.

**Comment by bjab** [comment]
I encountered same issue.
Maybe other option is to allow to configure service-worker to ignore some paths (like exclude all '/api/**') for example by taking in account `Cache-control: no-store` header.
Or maybe add option to `Http` module to force skipping service-worker.

**Comment by Eternahl** [comment]
@gdotdesign Before **adding tests**, are the **changes correct** ?
I did not use `npm@RouteParser` because the service-worker generation is outside `mint-runtime`.

Do you want me to add a "pull request draft" right now ?

**Comment by Eternahl** [comment]
> I'm not sure if using regexp is the way, the routes can match paths which the regexp would not match. For example, paths like this: `/page/:id/comments/:comment_id` that's why using `npm@RouteParser` would be desirable.

I agree with this.

How do you want to handle the import of this _package_ into the _service-worker_?
Maybe by exposing that _package_ from `mint-runtime`, then including that _runtime_ in the _service-worker_? but that doesn't seem relevant to me.

Am I missing something here?

**Comment by gdotdesign** [comment]
> How do you want to handle the import of this _package_ into the _service-worker_?
> Maybe by exposing that _package_ from `mint-runtime`, then including that _runtime_ in the _service-worker_? but that doesn't seem relevant to me.

The runtime is added into the final `index.js` so it's not available on its own, but maybe it should be. This is a good opportunity to separate it since we would use it in two places. Another option is just to include a pre-build version of route-parser in the production files and import that.

The third option would be to compile a matcher function in Crystal that we could embed in both places, which would remove the need for **route-parser** all together, but that's a bigger refactoring.

For me, all the options are fine :smile:
