### ISSUE TITLE
Case does not unify branches which can lead to unexpected behavior

### ISSUE THREAD

**Issue by greg-enbala** [mint-lang/mint#371]
Sorry for the poor title, I'm not sure of the exact nature of this bug. 

In this sandbox we can see an incorrect return type for `String.charCodeAt` accepted by the compiler. 
https://sandbox.mint-lang.com/sandboxes/FHqz8Btf_hwpKg

Here is the code from that sandbox:
```
component Main {
  fun render {
    <input value={Maybe.withDefault("", String.charCodeAt("hi", 0))}/>
  }
}

module String {
  fun charCodeAt (str : String, i : Number) : Maybe(String) {
    case (res) {
      -1 => Maybe.nothing()
      => Maybe.just(res)
    }
  } where {
    res =
      `#{str}.codePointAt(#{i}) || -1` as Number
  }
}
```

Bug:
`res` has a type hint of `as Number` and when sent to `case` it correctly type checks, but when wrapped in `Maybe.just` the compiler allows that to type check with `Maybe(String)` in the functions signature. This then type checks with `Maybe.withDefault("", __)`. If you remove all of the `Maybe`s and change the case to:
```
case res {
  -1 => ""
  => res
}
```
The code will be correctly rejected by the compiler with a type error.

Expected:
`Maybe(String)` should not unify with `Maybe.just(res)` as `res` has the type `Number`.

**Comment by gdotdesign** [comment]
First of all thanks for opening this issue, it was a tricky one so nice catch :pray: 

The reason `Maybe(String)` worked because a `case` statement used to use the type from the first branch which is a `Maybe::Nothing` with the type `Maybe(a)` what could be unified in with the return type.

The fix was to unify the a case branch with the previous one and use the last one as the type of the  `case` statement.

This change also revealed another bug in the `Result.join` function.
