### ISSUE TITLE
Consider using magickwand shard for image resizing

### ISSUE THREAD

**Issue by matthewmcgarvey** [mint-lang/mint#430]
To resize icons, Mint uses the ImageMagick `convert` CLI https://github.com/mint-lang/mint/blob/83ea006dee24a5f05feee1c4683e5b714f6a65a9/src/utils/icon_generator.cr#L13-L15

https://github.com/blocknotes/magickwand-crystal integrates directly with ImageMagick's c library instead of using the CLI.

## My Testing (https://github.com/matthewmcgarvey/mint/tree/mm/magickwand)

Current average `mint build`: 1.378s
Magickwand average `mint build`: 1.05s
Difference: .328s (**24% faster**)

## Caveat

The shard doesn't support Crystal 1.0.0 and hasn't been updated in almost 2 years. I was able to fork it and fix the shard.yml to work and it was fine. Someone will just need to fork the library and release a version to use in Mint.

**Comment by gdotdesign** [comment]
I think we went down this road before: https://github.com/mint-lang/mint/pull/296 https://github.com/mint-lang/mint/pull/300

There are two issues with this:
1. It just changes one dependency for an other - instead of needing ImageMagick itself it needs `libmagickwand`
2. It probably breaks static linking - The mint binary for Linux is statically linked on Alpine

The ideal solution would be if there were a pure Crystal image manipulation library.

**Comment by Sija** [comment]
> The ideal solution would be if there were a pure Crystal image manipulation library.

I second that. Before we'll get there (and personally I'd love to ditch ImageMagick altogether and see [`libvips`](https://github.com/libvips/libvips) ported) let's stay with the current approach.
