### ISSUE TITLE
Query params support

### ISSUE THREAD

**Issue by tkshnwesper** [mint-lang/mint#440]
Hello! 👋

I was wondering if it would be good to have query params support as part of the core mint language, or as part of an external library.

The implementation would look something like this:

```mint
Http.empty()
|> Http.url("https://httpbin.org/anything")
|> Http.queryParam("key", "value")
|> Http.queryParam("foo", "bar")
|> Http.send()
```

This will fire a request as follows

```
https://httpbin.org/anything?key=value&foo=bar
```

**Comment by gdotdesign** [comment]
There is already the [`SearchParams`](https://www.mint-lang.com/api/modules/SearchParams) module (which is a wrapper for [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)) for parsing and generating query strings:

```
query = 
  SearchParams.empty()
  |> SearchParams.append("key", "value")
  |> SearchParams.append("key2", "value2")
  |> SearchParams.toString()
```

which can be used in a request like this:

```
request = 
  Http.get("https://httpbin.org/anything?#{query}")
```

I would not add `Http.queryParam("key", "value")` since the query is actually part of the URL and not the request and would add complexity (we would need to parse the given URL for the query string, etc...).

We could add a functions to the [`Url`](https://www.mint-lang.com/api/modules/Url) module to manipulate an URLs query string, but I'm not sure about that either.

**Comment by tkshnwesper** [comment]
`SearchParams` is exactly the module I was looking for.

Perfect. Thank you!
