### ISSUE TITLE
Considering compiling to WebAssembly?

### ISSUE THREAD

**Issue by xtuc** [mint-lang/mint#45]
Hi :wave:,

From my experience new languages that target JavaScript are great, but they always have a trade-off for the same reason.

Since Mint has types, it should be possible to target WebAssembly instead. While it's quite new (and imposes some limitation at the moment), it's future proof IMO.

I would be happy to help/chat if you have questions.

**Comment by gdotdesign** [comment]
Hey :wave:,

Thanks for bringing this up! Here are my thoughts on the subject:
- WebAssembly is a really low-level language, compiling a high level language like Mint would be a huge effort.
- WebAssembly [does not have a GC yet](https://github.com/WebAssembly/design/issues/1079) that's why high level languages (like Crystal) don't usually compile to it.
- Since Mint uses React behind the scenes, we would need something similar to use which is written in WebAsssembly itself.
- It's true that Mint has types but they are not low level types (we have Number but no Float32, Float64, Int32, Int64, etc...)
- WebAssembly does not have interfaces for Web APIs yet.

All in all I don't think it's a good idea at this point to compile to WebAssembly. Maybe in the future when it's matured enough and have good developer tools to make it easier.

However anyone is welcome to create a proof of concept which we expand upon, I think the AST is pretty is easy to navigate and there is enough separation to create a new compiler target.

**Comment by xtuc** [comment]
> WebAssembly does not have a GC yet that's why high level languages (like Crystal) don't usually compile to it.

Sorry i'm have no experience with Crystal, but since you mentioned I'm assuming that Cyrstal is garbage collected. 

> It's true that Mint has types but they are not low level types (we have Number but no Float32, Float64, Int32, Int64, etc...)

Ok, I assumed that it was strongly typed.

> WebAssembly does not have interfaces for Web APIs yet.

Yes that's what I meant with limitations, a workaround is to generate glue code in JavaScript to marshall/unmarshall datastructures.

---

You might want to close this, it's too early.
