### ISSUE TITLE
Formatter breaks words into multiple lines

### ISSUE THREAD

**Issue by Sija** [mint-lang/mint#471]
I'd expect the formatter to break the long strings with respect to keeping the words intact, instead, it breaks them:

```cr
"some of the words are bro" # <- see here
"ken into multiple lines"
```

**Comment by gdotdesign** [comment]
This was fixed in `0.20.0` https://github.com/mint-lang/mint/blob/master/spec/formatters/string_literal_split as part of the formatter refactor https://github.com/mint-lang/mint/blob/master/src/formatter/processor.cr#L55-L99. It tries to keep words, but if the word is bigger than a hole line it will split that.
