### ISSUE TITLE
Add a minimum of reflection for automatic JSON.

### ISSUE THREAD

**Issue by Camto** [mint-lang/mint#48]
It would be nice for the language to have at least enough reflection for a JSON decoder/encoder to be automatically makeable without using external tools, just with code. This would be to have less boilerplate. And possibly other serialization formats (Protobuf, XML) to be easier to add as libraries.

Edit: I saw Rust had `#[derive(Debug)]` and Haskell had something similar with `Show`, so that's an idea.

**Comment by gdotdesign** [comment]
Thanks for creating this issue!

Mint has automatic `Object` (it represents a JavaScript value) encoding / decoding for primitive structures, so you can already do this:
```
record User {
  name : String,
  age : Number
}

component Main {
  property user : User = {
    name = "John Doe",
    age = 31
  }
  
  get encodedUser : Object {
    encode user
  }
  
  get decodedUser : User {
    try { 
      decoded = 
      	decode encodedUser as User
    } catch Object.Error => error {
      user
    }
  }
  
  fun render : Html {
    <div>
      <{ decodedUser.name }>
      <{ Number.toString(decodedUser.age) }>
    </div>
  }
}
```
then objects can be converted to JSON using `Json.stringify(object)`

Since Mint has JavaScript inlining existing libraries can be used to convert these objects to specific formats. For now I don't think it is necessary to have reflection in the language.

You can read more about the decoding here: 
https://guide.mint-lang.com/reference/javascript-interop/decoding-objects
and inlining here: 
https://guide.mint-lang.com/reference/javascript-interop/javascript-interop

**Comment by gdotdesign** [comment]
I'm closing this issue because the question is answered and that was the last  inactivity (30+ days ago).
