### ISSUE TITLE
Label inside loop still triggers checkbox after removal

### ISSUE THREAD

**Issue by michaelowens** [mint-lang/mint#545]
When making a todo list I ran into an issue that having a delete icon would update the next items status. I can't seem to log in on the sandbox due to a redirect_uri error, so I'll put my example reproducing the issue here.

If you press the X on the first item, it will remove the item but now the remaining item will suddenly be checked. This also triggers a change event on the checkbox, causing possible side effects. I wouldn't expect this to happen, as the click was done on the item that was deleted, but I'm guessing the checkbox is being reused from the first item when re-rendering.

```mint
record TodoItem {
  text : String,
  done : Bool
}

component Main {
  state items : Array(TodoItem) = []

  style label {
    display: block;
  }

  style delete {
    cursor: pointer;
    margin-left: 5px;
    color: red;
  }

  fun componentDidMount {
    next {
      items = [
        TodoItem("one", true),
        TodoItem("two", false),
      ]
    }
  }

  fun render : Html {
    <div>
      "Delete the first item and it will check the remaining item"
      <{ Array.mapWithIndex((item: TodoItem, index: Number) {
        <label::label>
          <input type="checkbox" />
          <{ item.text }>
          <span::delete onClick={() { next { items = Array.deleteAt(index, items) } }}>"X"</span>
        </label>
      }, items) }>
    </div>
  }
}
```

**Comment by gdotdesign** [comment]
There are two issues:

1. The label is associated with the input, so clicking on the span triggers the click on the label as well, which triggers the change event on the input. You can prevent this if you call `Html.Event.preventDefault` on the click event.
2. Since we are using a virtual DOM, we need to specify the key for each item in a list using the `key` attribute. This article explains it nicely: https://reactjs.org/docs/lists-and-keys.html

I've updated the code and put it on the sandbox: https://sandbox.mint-lang.com/sandboxes/7cVcuRTxgAZR8w

> I can't seem to log in on the sandbox due to a redirect_uri error, so I'll put my example reproducing the issue here.

Thank you for reporting, it should be fixed now (we moved from `www` to naked domain which caused this)

**Comment by michaelowens** [comment]
Ah, I was actually looking for either of those as a solution, but I probably didn't look through the docs well enough. Thanks for clearing that up.

After looking a the [Handling Events](https://mint-lang.com/guide/getting-started/handling-events)-page and seeing it was a record without any functions, I forgot to look at the API docs. Maybe it's worth mentioning that there are functions on Html.Event and linking/referring to the API docs.
