### ISSUE TITLE
the name fun vs function

### ISSUE THREAD

**Issue by mikkifr** [mint-lang/mint#55]
Is there a reason why functions are call "fun" but things like components, modules, and records are not called  "com", "mod" and "rec?"

**Comment by gdotdesign** [comment]
The its called `fun` instead of `function` because:

1. it's more common then the other entity type keywords (`component`, `module`, `record`, etc...)
2. it's the same number of characters as `get` so the most used entities in a component / module / store  `fun` and `get` line up
3. as an abbreviation is pretty clear while `com`, `mod` and `rec` are not

**Comment by kvnxiao** [comment]
👍 for choosing `fun` because it reminds me of `kotlin` :^)

**Comment by kingsleyh** [comment]
I agree - `fun` is a nice easy short name for something we use a lot.

**Comment by gdotdesign** [comment]
Closing since people are OK with the `fun` keyword. Added the question to the README.

**Comment by handicraftsman** [comment]
mod is pretty ok for me. It's also used in rust.
