### ISSUE TITLE
What makes Mint unique?

### ISSUE THREAD

**Issue by DanielSokil** [mint-lang/mint#70]
For example Elm offers no runtime exceptions, which is amazing.
What makes Mint amazing ?

**Comment by handicraftsman** [comment]
Embedded features of libraries like React, Redux, Aphrodite, etc.

**Comment by gdotdesign** [comment]
Pretty much what @handicraftsman wrote. In Mint everything is built in so to speak.

I'm writing a post about comparing it with a popular JavaScript stack (which I post here when ready), in it I compare **are all the things Mint has built in** to their counterpart in the JS stack:
- view (virtual DOM) -> react
- global state handling -> redux
- routing -> react-router
- formatter -> prettier
- development server + production building -> webpack (babel and it's plugins)
- package manager -> npm
- type checker -> flow
- documentation generator -> esdoc
- styling -> styled-components
- testing framework -> jest, enzyme

On top of this there are 300+ nice error messages, easy JS interopability and probably some small features I am forgetting. 

Mint is still young there will be more features added in the future check them out on the [roadmap](https://www.mint-lang.com/roadmap).

**Comment by DanielSokil** [comment]
@gdotdesign  So Mint integrates does libraries behind the scenes? Or just offers what those libraries offer?

**Comment by gdotdesign** [comment]
@DanielSokil It just offers what those libraries offer, except React which is integrated as the view layer.

**Comment by gdotdesign** [comment]
I think bundle size using Mint can be generally kept low, the "runtime" (https://github.com/mint-lang/mint-runtime) currently is ~150kb minified, 100kb of which is React.

The bundle size of the Mint website (https://github.com/mint-lang/mint-website) is 69kb gzipped (~280kb extracted) which contains the styles as well.

There are two things that could make this even smaller:
- dead code elimination - because of the type checking in theory, not used components / modules / functions could be removed during compilation, it's something I'm planning to implement in the future
- replace React with something smaller, possibly Preact. For this I need to experiment to see if all the features needed are supported.

**Comment by DanielSokil** [comment]
@gdotdesign For dead code elimination, would I need to use a tool like rollup, or that feature will be built into Mint?

**Comment by gdotdesign** [comment]
@DanielSokil It will be built into Mint.

**Comment by gdotdesign** [comment]
I've added the question to the readme pointing to this thread, so I'm closing this.

**Comment by DanielSokil** [comment]
@gdotdesign Thanks very much for your detailed responses.

**Comment by tigp** [comment]
Preact would significantly lower the  size

**Comment by tigp** [comment]
Very interesting language!
