### ISSUE TITLE
Allow multiple style blocks on the same html element

### ISSUE THREAD

**Issue by steevehook** [mint-lang/mint#99]
Hi guys, first of all I love the project and would love to get involved as a contributor. It's quite promising and I like the prototype so far.

A quick proposal on my end. So I played a little bit with components and styling and maybe this is not documented or something but would really love the language to support multiple style blocks per element:

Here's a dummy component

```
component Welcome {
    property name : String = "Welcome buddy"

    style main {
        color: red;
    }

    style name {
        color: green;
    }

    style font {
        font-size: 18px;
    }

    fun render : Html {
        <div>
            <h1::main><{"Hello"}></h1>
            <h2::name><{name}></h2>
        </div>
    }
}
```

If for example I wanted to apply font style on both elements I don't know how do do it.

I tried separating by **comma** or by **::** and it did not work

My proposal would be to separate them by **::** to have something like this:

```
component Welcome {
    property name : String = "Welcome buddy"

    style main {
        color: red;
    }

    style name {
        color: green;
    }

    style font {
        font-size: 18px;
    }

    fun render : Html {
        <div>
            <h1::main::font><{"Hello"}></h1>
            <h2::name::font><{name}></h2>
        </div>
    }
}
```

This way we can reuse styles across the component elements themselves
Thanks, let me know if I can help with a PR or something

**Comment by gdotdesign** [comment]
It's something that I thought about too, but I could not find much uses cases for it.

Your example can be modified to work without it since CSS cascading still works:
```
component Welcome {
  property name : String = "Welcome buddy"

  style main {
    color: red;
  }

  style name {
    color: green;
  }

  style font {
    font-size: 18px;
  }

  fun render : Html {
    <div::font>
      <h1::main><{"Hello"}></h1>
      <h2::name><{name}></h2>
    </div>
  }
}
```

We can add it if there is a need for it, there some questions for the implementation if we do:
* in what the order the styles applied
* what value of a property is applied if there are multiple properties with the same name
* what would the syntax be (I like the double colon separator)

> Thanks, let me know if I can help with a PR or something

The best way you can help right now is to write things in Mint :+1: and let me know about any issues you face, or if something is not clear or if the documentation is lacking and of course telling everybody how awesome it is :grin:

**Comment by steevehook** [comment]
It's seems a bit odd that styles are part of the element body. As you illustrated above. Plus you can't really use patterns like BEM. Or at least have some reasonable way of having inheritance. In the case of 2 classes in no big deal. However in real world there might be more. And having them separated by :: makes it easy readable and of course the order of cascading is as they appear from left to right

Making it as CSS compatible as possible I think is best. Which will also lead less to a dead language

**Comment by Sija** [comment]
Maybe CSS like `.` separator could work? It has bonus of familiarity.

**Comment by gdotdesign** [comment]
Merging with #128
